### ISSUE TITLE
Could not find "markdown" reporter

### ISSUE THREAD

**Issue by skemp-PCS** [cmaccorm/newman-reporter-markdown#3]
I installed the reporter via
```npm install -g newman-reporter-basicmarkdown```

When trying to run my collection using the command
```newman run "XXX.postman_collection.json" -e "XXX.postman_environment.json" -r markdown```
I am getting the error
```
newman: could not find "markdown" reporter
  ensure that the reporter is installed in the same directory as newman
  please install reporter using npm
```

**Comment by nitjsefni-bert** [comment]
Hello, 

just use:

newman run "XXX.postman_collection.json" -e "XXX.postman_environment.json" --reporters basicmarkdown --reporter-basicmarkdown-export ../results/examplefile.txt

**Comment by skemp-PCS** [comment]
Thank you very much for the information, this has worked perfectly.
Hopefully, the documentation can be updated to reflect how it's supposed to work
